// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;
import service1.service2;

listener http:Listener ep0 = new (9090);

// Structured error body for any path/method this service does not serve —
// the shared Error shape from the component's openapi.yaml. Not referenced by
// service1's own spec (it documents only the 200 on /average-score), so the
// generator did not emit a type for it; this record mirrors that schema for
// use outside the documented contract.
type ErrorPayload record {|
    int code;
    string message;
    string description?;
|};

service / on ep0 {
    resource function get average\-score() returns AverageScore|error {
        service2:Catalog catalog = check service2Client->/catalog.get();
        service2:Record[] records = catalog.records;
        log:printInfo("handled average-score request", recordCount = records.length());
        int total = 0;
        foreach service2:Record r in records {
            total += r.score;
        }
        int average = records.length() == 0 ? 0 : total / records.length();
        return {average: average};
    }

    // Catch-all: any path/method this service does not serve.
    resource function 'default [string... path]() returns http:NotFound {
        ErrorPayload body = {code: 404, message: "Not Found", description: "The requested resource was not found."};
        return <http:NotFound>{body: body};
    }
}

public type AverageScore record {
    # Sum of every record's score divided by the record count, remainder discarded
    int average;
};
