// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The catalog service2 currently serves (full or empty, by mode)
    #
    # + return - The current catalog
    resource function get catalog() returns Catalog {
        Record[] currentRecords = currentCatalogRecords();
        log:printInfo("handled GET /catalog request", recordCount = currentRecords.length());
        return {records: currentRecords};
    }

    resource function put catalog\-mode(@http:Payload CatalogModeUpdate payload) returns CatalogModeState|ErrorBadRequest {
        string requestedMode = payload.mode;
        if requestedMode != "full" && requestedMode != "empty" {
            Error errorBody = {code: 400, message: "invalid catalog mode", description: "mode must be one of 'full' or 'empty'"};
            return <ErrorBadRequest>{body: errorBody};
        }
        setCatalogMode(requestedMode);
        Record[] currentRecords = currentCatalogRecords();
        log:printInfo("handled PUT /catalog-mode request", recordCount = currentRecords.length());
        return {mode: <"full"|"empty">requestedMode};
    }
}

public type CatalogModeState record {
    "full"|"empty" mode;
};

public type CatalogModeUpdate record {
    string mode;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type Record record {
    int id;
    string name;
    int score;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type Catalog record {
    Record[] records;
};
